### ISSUE TITLE
Hi, i need some help with your shell

### ISSUE THREAD

**Issue by ghost** [chihwan/ethos_mario_rig#4]
「add watchdog.sh for auto restarting mining in case of low watt」
can you write an article about watchdog teaching ?
I will thank you very much !

**Comment by chihwan** [comment]
Technically this code is not working on current version of ethos 1.2.9.
In the current version, it is not possible for restarting mining without reboot.
But if you want to use this code, you would better to use ethos 1.2.7. Because I only tested on 13way Nvidia GTX 1060 on version 1.2.7. So AMD graphic cards won't be working on it. 

By the way, this code is very simple. It detects NVIDIA graphic cards lower than 55 watts using nvidia-smi command. So if cards detected then restart mining. That's all. 

And I will close this issue.

**Comment by ghost** [comment]
ok , thx all 
Can I use the GPU at Amd?

**Comment by chihwan** [comment]
No, you can not. It uses 'nvidia-smi' command ,so amd is not working.
